version: "3.8"
services:
  flask-app:
    container_name: reu_game
    build:
        context: .
        dockerfile: Dockerfile-dev
    stdin_open: true
    tty: true
    ports:
      - "8080:8080"
    volumes:
      - .:/app


  
